cakes_world/urls.py
from django.contrib import admin
from django.urls import path,include
from home import views

urlpatterns = [
    path("admin/", admin.site.urls),
    path('',views.index,name="index"),
    path('home/',include('home.urls',namespace='home')),
]

home/urls.py
from django.urls import path
from . import views
app_name='home'
urlpatterns=[
    path('cake',views.cake,name='cake'),
    path('pastries',views.pastries,name='pastries'),
    path('signup',views.signup,name='signup'),
    path('order',views.order,name='order'),
    path('success',views.success,name='success'),
    path('signup',views.signup,name='signup'),
    path('login',views.logIn,name='login'),
    path('logout',views.logOut,name='logout'),
]

home/models.py
from django.db import models
from django.contrib.auth.models import User
class Cake(models.Model):
   name=models.CharField(max_length=100)
   priceS=models.IntegerField(default=100)
   priceM=models.IntegerField(default=100)
   priceL=models.IntegerField(default=100)
   images=models.URLField()




class Pastrie(models.Model):
   name=models.CharField(max_length=100)
   priceS=models.IntegerField(default=100)
   priceM=models.IntegerField(default=100)
   priceL=models.IntegerField(default=100)
   images=models.URLField()

home/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
class NewUserForm(UserCreationForm):
    email=forms.EmailField(max_length=100,required=True,help_text='Inform a valid mailId')
    class Meta:
        model=User
        fields=['username','email','password1','password2']

home/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponse,JsonResponse
from .models import Cake,Pastrie
from .forms import NewUserForm
from django.contrib.auth.forms import UserCreationForm
from django.views.decorators.csrf import csrf_exempt
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import authenticate,login,logout
from django.contrib import messages
def index(request):
    request.session.set_expiry(0)
    ctx={'active_link':'index'}
    return render(request,'home/index.html',ctx)
def cake(request):
    request.session.set_expiry(0)
    cakes=Cake.objects.all()
    ctx={'cakes':cakes,'active_link':'Cake'}
    return render(request,'home/cake.html',ctx)
def pastries(request):
    request.session.set_expiry(0)
    pastries=Pastrie.objects.all()
    ctx={'pastries':pastries,'active_link':'Pastrie'}
    return render(request,'home/pastries.html',ctx)
def signup(request):
    request.session.set_expiry(0)
    ctx={}
    if request.POST:
        form=NewUserForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('index')
        else:
            ctx['form']=form
    else:
        form=NewUserForm()
        ctx['form']=form
    return render(request,'home/signup.html',ctx) 

@csrf_exempt
def order(request):
    request.session.set_expiry(0)
    if request.headers.get('X-Requested-With') == 'XMLHttpRequest':
        request.session['note'] = request.POST.get('note')
        request.session['orders'] = request.POST.get('orders')
        print(request.session['note'])
        order=request.POST.get('orders')
        print(order)
        return JsonResponse({'message': 'Data received successfully'})
    ctx = {'active_link': 'order'}
    return render(request, 'home/order.html', ctx)
def success(request):
    # order=request.session['order']
    # ctx={'order':order}
    return render(request,'home/success.html')
def signup(request):
    ctx={}
    if request.POST:
        form=NewUserForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('index')
        else:
            ctx['form']=form
    else:
        form=NewUserForm()
        ctx['form']=form
    return render(request,'home/signup.html',ctx)
def logIn(request):
    if request.POST:
        username=request.POST.get('username')
        pwd=request.POST.get('password')
        user=authenticate(request,username=username,password=pwd)
        if user is not None:
            login(request,user)
            return redirect('index')
        else:
            messages.info(request,'username and/or password are incorrect')
    ctx={'active_link':'login'}
    return render(request,'home/login.html',ctx)
def logOut(request):
    logout(request)
    return redirect('index')

home/templates/home/cake.html
{%extends 'home/base.html' %}
{%load static%}
{% block title %}Cakes{%endblock%}
{%block content%}
    <div class="container-fluid">
      <div class="row ">
        <div class="col-md-8 text-center">
          <h2 class="title">Our Cakes</h2>
          <div class="row">
            {%for cake in cakes %}
            <div class="col-md-4 p-4">
             <img class="picture" src="{{cake.images}}">
             <h4 class="pt-3" id="cak{{cake.id}}">{{cake.name}}</h4>
             <div class="form-check-inline">
              <label class="form-check-label">
                <b>Small</b>
                <input class="form-check-input" type="radio" name="cake{{cake.id}}" value="{{cake.priceS}}" checked>
                Rs.{{cake.priceS}} 
              </label>
             </div>
             <div class="form-check-inline">
              <label class="form-check-label">
                <b>Medium</b>
                <input class="form-check-input"value="{{cake.priceM}}" name="cake{{cake.id}}" type="radio" >
                Rs.{{cake.priceM}}
              </label>
             </div>
             <div class="form-check-inline">
              <label class="form-check-label">
                <b>Large</b>
                <input class="form-check-input" value="{{cake.priceL}}"name="cake{{cake.id}}" type="radio" >
                  Rs.{{cake.priceL}}
                
              </label>
             </div>
             <div> 
             <button class="btn-info mt-3" onclick="addCake('{{cake.id}}')">Add to Cart</button>
             </div>


           </div>
            {% endfor %}
          </div>
        </div>
        <div class="col-md-4 orders">
          <div class="bg-dark text-light p-4"> 
          <h2 class="text-center">Order list</h2>
            <ul id="pcart"></ul>
            <h4 id="ptotal" class="text-right"> Total: 0Rs</h4>
          </div>
        </div>
      </div>
    </div>  
    <script src="{%static 'home/js/order.js' %}" ></script>  
    <script>
      pshoppingcart();
    </script>    
{%endblock%}

home/templates/home/index.html
{%extends 'home/base.html' %}
{% block title %}Home{%endblock%}
{% block content %}
<div class="home">
    <h1> KANISHK pAeek</h1>

</div>

{%endblock%}

home/templates/home/login.html
{%extends 'home/base.html' %}
{% block title %}Login{%endblock%}
{%block content%}
<div class="container-fluid p-5">
    <div class="row">
        <div class="col-md-3"></div>
        <div class="col-md-6 p-4 bg-dark text-light text-center">
            <h3 >Login</h3>
            <a href="{%url 'home:signup'%}" >Sign Up</a>
            <form method="POST" class="p-2">
                {% csrf_token %}
                <div class="form-group">
                    <input type="text"name="username" placeholder="Username">

                </div>
                <div class="form-group">
                    <input type="password"name="password" placeholder="*********">
                </div>
                <div>
                    {%for error in form.errors%}
                    <small style="color:red">{{error}}</small>
                    {%endfor%}
                </div> 
                <button type="submit" class="btn-info">Login</button>
                {% if messages %}
                  <ul class="pt-2 text-center">
                    {% for msg in messages%}
                    <li style="color:red";>{{msg}}</li>
                    {%endfor%}
                  </ul>
                  {%endif%}
            </form>

        </div>
        <div class="col-md-3">
        </div>
    </div>
</div>

{%endblock%}

home/templates/home/order.html
{% extends 'home/base.html' %}
{% load static %}
{% block title %}Orders{% endblock %}

{% block content %}
<div class="container-fluid m-4">
    {%if user.is_authenticated%}
        <h2> Welcome {{user.username}}</h2>
        {%endif%}
    <div class="row">
        <div class="col-md-7 text-center">
            <h2>Order</h2>
            <div class="row">
                <div class="col-md-3" id="names">
                    <h3>Name</h3>
                </div>
                <div class="col-md-3" id="size">
                    <h3>Size</h3>
                </div>
                <div class="col-md-3" id="price">
                    <h3>Price</h3>
                </div>
                <div class="col-md-1" id="rm">
                </div>
            </div>
            <h2 id="total">Total:</h2>
        </div>
        <div class="col-md-5 mt-4">
            <h2>Message</h2>
            <textarea name="message" id="message" cols="40" rows="5"></textarea>
            {%if user.is_authenticated%}
            <div class="ml-auto m-4">
                <button type="submit" class="btn-success" onclick="order()">Submit</button>
            </div>
            {%else%}
            <div class="ml-auto m-4">
                <a href="{%url 'home:login'%}">Log In</a>
            </div> 
            {%endif%}
        </div>
    </div>
</div>
<script src="{% static 'home/js/cart.js' %}"></script>
<script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>
{% endblock %}

home/templates/home/pastries.html
{% extends 'home/base.html' %}
{% load static %}
{% block title %}Pastries{% endblock %}
{% block content %}
  <div class="container-fluid">
    <div class="row">
      <div class="col-md-8 text-center">
        <h2 class="title">Our Pastries</h2>
        <div class="row">
          {% for pastry in pastries %}
          <div class="col-md-4 p-4">
            <img class="picture" src="{{ pastry.images }}">
            <h4 class="pt-3" id="pas{{ pastry.id }}">{{ pastry.name }}</h4>
            <div class="form-check-inline">
              <label class="form-check-label">
                <b>Small</b>
                <input class="form-check-input" id="pastryS{{ pastry.id }}" value="{{ pastry.priceS }}" name="pastry{{ pastry.id }}" type="radio" checked>
                Rs.{{ pastry.priceS }}
              </label>
            </div>
            <div class="form-check-inline">
              <label class="form-check-label">
                <b>Medium</b>
                <input class="form-check-input" id="pastryM{{ pastry.id }}" value="{{ pastry.priceM }}" name="pastry{{ pastry.id }}" type="radio">
                Rs.{{ pastry.priceM }}
              </label>
            </div>
            <div class="form-check-inline">
              <label class="form-check-label">
                <b>Large</b>
                <input class="form-check-input" id="pastryL{{ pastry.id }}" value="{{ pastry.priceL }}" name="pastry{{ pastry.id }}" type="radio">
                Rs.{{ pastry.priceL }}
              </label>
            </div>
            <div>
              <button class="btn-info mt-3" onclick="addPastry('{{ pastry.id }}')">Add to Cart</button>
            </div>
          </div>
          {% endfor %}
        </div>
      </div>
      <div class="col-md-4 orders">
        <div class="bg-dark text-light p-4">
          <h2 class="text-center">Order list</h2>
          <ul id="bcart"></ul>
          <h4 id="btotal" class="text-right">Total: Rs.0</h4>
        </div>
      </div>
    </div>
  </div>
  <script src="{% static 'home/js/borders.js' %}"></script>
  <script>
    bshoppingcart();
  </script>
{% endblock %}

home/templates/home/signup.html
{%extends 'home/base.html' %}
{% block title %}SignUp{%endblock%}
{%block content%}
<div class="container-fluid p-5">
    <div class="row">
        <div class="col-md-3"></div>
        <div class="col-md-6 p-4 bg-dark text-light text-center">
            <h3 >SignUp</h3>
            <a href="{%url 'home:login'%}" >Log In</a>
            <form method="POST" class="p-2">
                {% csrf_token %}
                {% for field in form %}
                <div class="form-group">
                    <div>{{ field.label_tag }}</div>
                    <div>
                        {{ field }}
                    </div>
                    {% if field.help_text%}
                    <small style="color:grey">{{field.help_text}}</small>
                    {%endif%}
                </div>

                {% endfor %}
                <div>
                    {%for error in form.errors%}
                    <small style="color:red">{{error}}</small>
                    {%endfor%}
                </div> 
                <button type="submit" class="btn-info">SignUp</button>
            </form>

        </div>
        <div class="col-md-3">
        </div>
    </div>
</div>

{%endblock%}
{% comment %} {% extends 'home/base.html'%}
{% block title %}SignUp{% endblock %}
{% block cotntent %}
{% load static %}
    
{% endblock %} {% endcomment %}

home/templates/home/success.html
{% extends 'home/base.html' %}
{% load static %}
{% block title %}Success{% endblock %}

{% block content %}
<div class="container-fluid">
    <h2>We have recived your order</h2>
    <h3>You have ordered some items</h3>
    {% comment %} <h4> {{order}}</h4> {% endcomment %}
    <h4> if You want to modify your order please call us</h4>
    <h4> Phone: 9694668873</h4>
</div>
{%endblock%}